<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>86a492f0-bb0e-476d-bbc6-5686147c0e1d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="MySqlConnector" Version="2.6.1" />
    <PackageReference Include="Stripe.net" Version="42.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mapping\" />
    <Folder Include="Configuration\" />
    <Folder Include="Extensions\" />
    <Folder Include="Constants\" />
    <Folder Include="Enums\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Library_Management.Tests\**" />
    <EmbeddedResource Remove="Library_Management.Tests\**" />
    <None Remove="Library_Management.Tests\**" />
    <Content Remove="Library_Management.Tests\**" />
  </ItemGroup>

</Project>
